environment: dev
namespacePrefix: default-app
storageClassName: nfs-dev
image:
  registry: docker.io
  namespace: afekio
  tag: latest
replicas: 1
dbInstances: 1
ingress:
  host: default-app.local
grafana:
  rootUrl: http://default-app.local/grafana/