
# --- Stage 2: Nginx Server ---
FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY ./dist /usr/share/nginx/html
RUN mkdir -p /var/cache/nginx /var/run \
	&& chown -R nginx:nginx /var/cache/nginx /var/run /usr/share/nginx/html /etc/nginx
EXPOSE 8080
USER nginx
CMD ["nginx", "-g", "daemon off;"]