FROM nginx:1.27-alpine
COPY ./dist /usr/share/nginx/html

# Create the PID file explicitly and set ownership specifically, avoiding the rest of /var/run
# Also adding /var/log/nginx just to be absolutely safe with permissions
RUN mkdir -p /var/cache/nginx /var/log/nginx \
    && touch /var/run/nginx.pid \
    && chown -R nginx:nginx /var/cache/nginx /var/log/nginx /var/run/nginx.pid /usr/share/nginx/html /etc/nginx

EXPOSE 8080
USER nginx
CMD ["nginx", "-g", "daemon off;"]