version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: admindb
      POSTGRES_PASSWORD: {IN-VAR}
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth:
    build: ./Auth
    container_name: local_auth
    restart: always
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://admindb:{IN-VAR}:5432/appdb
      - SECRET_KEY={IN-VAR}
      - SHARED_DIR=/shared_files
    volumes:
      - shared_files:/shared_files
      - ./Logs/Auth:/app/logs
    depends_on:
      - db

  backend:
    build: ./Backend
    container_name: local_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - AUTH_URL=http://auth:5001
      - SECRET_KEY={IN-VAR}
      - SHARED_DIR=/shared_files
    volumes:
      - shared_files:/shared_files
      - ./Logs/Backend:/app/Logs
      - ./Backend/Configs:/app/Configs
      - ./Backend/Scripts:/app/Scripts
    depends_on:
      - auth

  frontend:
    build: ./Frontend
    container_name: local_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - auth
      - backend

volumes:
  pgdata:
  shared_files:
