apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-conf
  namespace: {{ .Values.namespacePrefix }}-frontend
data:
  default.conf: |
    server {
        listen 8080;
        server_name _;
        
        root /usr/share/nginx/html;
        index index.html;
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        location /health {
            default_type application/json;
            return 200 '{"status": "ok", "service": "frontend"}';
        }

        location / {
            try_files $uri $uri/ /index.html;
            add_header Cache-Control "no-store, no-cache, must-revalidate";
        }
    }