apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-logs
  namespace: {{ .Values.namespacePrefix }}-auth
spec:
  accessModes: [ReadWriteMany]
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-logs
  namespace: {{ .Values.namespacePrefix }}-backend
spec:
  accessModes: [ReadWriteMany]
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: 2Gi