apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-logs
  namespace: {{ .Values.namespacePrefix }}-auth
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-prod
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-logs
  namespace: {{ .Values.namespacePrefix }}-backend
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-prod
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-configs
  namespace: {{ .Values.namespacePrefix }}-backend
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-prod
  resources:
    requests:
      storage: 2Gi