apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: dev-postgres
  namespace: dev-postgres
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  bootstrap:
    initdb:
      database: appdb
      owner: app_user
      secret:
        name: app-database-credentials
  storage:
    size: 20Gi
    storageClass: nfs-prod
  superuserSecret:
    name: app-postgres-superuser
  managed:
    roles:
      - name: app_user
        ensure: present
        login: true
        passwordSecret:
          name: app-database-credentials
