apiVersion: v1
kind: Namespace
metadata:
  name: dev-frontend
  labels:
    app.kubernetes.io/environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-backend
  labels:
    app.kubernetes.io/environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-postgres
  labels:
    app.kubernetes.io/environment: dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-logs
  namespace: dev-backend
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-prod
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-logs
  namespace: dev-backend
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-prod
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-files
  namespace: dev-backend
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-prod
  resources:
    requests:
      storage: 10Gi