environment: dev
imagePullSecrets: []

images:
  auth: afekio/auth
  backend: afekio/backend
  frontend: afekio/frontend
  tag: <YOUR_IMAGE_TAG>

secrets:
  authSecretName: app-auth-secrets
  databaseSecretName: app-database-secrets
  databaseUrl: postgresql://app_user:<YOUR_DATABASE_PASSWORD>@dev-postgres-rw.dev-postgres.svc.cluster.local:5432/appdb

storage:
  storageClass: nfs-prod
  authLogsSize: 2Gi
  backendLogsSize: 2Gi
  backendFilesSize: 10Gi

postgres:
  namespace: dev-postgres
  clusterName: dev-postgres
  instances: 3
  storageClass: nfs-prod
  storageSize: 20Gi
  database: appdb
  owner: app_user

network:
  frontendNamespace: dev-frontend
  authNamespace: dev-auth
  backendNamespace: dev-backend
  postgresNamespace: dev-postgres
