---
- name: Install operating system prerequisites
  ansible.builtin.package:
    name:
      - curl
      - ca-certificates
      - iptables
      - tar
    state: present

- name: Set timezone to jerusalem
  ansible.builtin.timezone:
    name: Asia/Jerusalem

- name: set rtc to true
  ansible.builtin.command: timedatectl set-local-rtc 1
  
- name: Load required kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Persist required kernel modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/rke2.conf
    content: |
      overlay
      br_netfilter
    mode: "0644"

- name: Configure Kubernetes sysctl values
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop:
    - { name: net.bridge.bridge-nf-call-iptables, value: "1" }
    - { name: net.bridge.bridge-nf-call-ip6tables, value: "1" }
    - { name: net.ipv4.ip_forward, value: "1" }

- name: Disable IPv6 on all nodes
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Remove IPv6 localhost entry from /etc/hosts
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: '^::1.*'
    replace: ''

- name: Restart RKE2 server to apply IPv4-only networking (Master only)
  ansible.builtin.systemd:
    name: rke2-server
    state: restarted
  when: inventory_hostname == 'rke2-control-panel'

- name: Restart RKE2 agent to apply IPv4-only networking (Workers only)
  ansible.builtin.systemd:
    name: rke2-agent
    state: restarted
  when: inventory_hostname == 'rke2-node01' or inventory_hostname == 'rke2-node02'