vault_rke2_token: "changeme"
vault_jenkins_admin_password: "changeme"
vault_dockerhub_token: "need to create api token on docker hub and paste here"

vault_dev_jwt_secret: "changeme"

vault_dev_internal_auth_secret: "changeme"

vault_dev_database_password: "changeme"

vault_dev_postgres_superuser_password: "changeme"