---
- name: Install NFS client package
  ansible.builtin.package:
    name: nfs-common
    state: present

- name: Create NFS mount directory
  ansible.builtin.file:
    path: "{{ nfs_server.mount_path }}"
    state: directory

- name: Mount RKE2 NFS export
  ansible.posix.mount:
    src: "{{ nfs_server.hostname }}:{{ nfs_server.export_path }}"
    path: "{{ nfs_server.mount_path }}"
    fstype: nfs4
    opts: "{{ nfs_server.mount_options }}"
    state: mounted