---
all:
  vars:
    ansible_user: user
  children:
    rke2_servers:
      hosts:
        rke2-control-panel:
          # Current reachable address. Change to the static address after first run.
          ansible_host: 192.168.115.128
          # Replace with the SSH user that exists on the control panel.
          ansible_user: ubuntu
    rke2_agents:
      hosts:
        rke2-node01:
          ansible_host: 192.168.115.138
        rke2-node02:
          ansible_host: 192.168.115.141
    nfs_servers:
      hosts:
        rke-nfs-server:
          ansible_host: 192.168.115.140