---
- name: Create RKE2 configuration directory
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    mode: "0750"

- name: Render RKE2 server configuration
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    mode: "0600"
  notify: Restart RKE2 server

- name: Install RKE2 server
  ansible.builtin.shell: |
    set -o pipefail
    curl -sfL https://get.rke2.io | {{ rke2_install_environment }} sh -
  args:
    executable: /bin/bash
    creates: /usr/local/bin/rke2
  vars:
    rke2_install_environment: >-
      INSTALL_RKE2_TYPE=server
      {% if rke2_version | length > 0 %}INSTALL_RKE2_VERSION={{ rke2_version }}{% else %}INSTALL_RKE2_CHANNEL={{ rke2_channel }}{% endif %}

- name: Enable and start RKE2 server
  ansible.builtin.systemd:
    name: rke2-server.service
    enabled: true
    state: started

- name: Network & DNS Configuration
  block:
    - name: Configure Google and Cloudflare DNS in systemd-resolved
      ansible.builtin.lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^#?DNS='
        line: 'DNS=8.8.8.8 1.1.1.1'
        state: present
      notify: Restart systemd-resolved

    - name: Symlink systemd-resolved stub to /etc/resolv.conf
      ansible.builtin.file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link
        force: yes

# ==========================================
# Automated CoreDNS Patching (Force TCP & External DNS)
# ==========================================
- name: Wait for CoreDNS ConfigMap to be created
  ansible.builtin.command:
    cmd: /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get configmap rke2-coredns-rke2-coredns -n kube-system
  register: coredns_cm
  retries: 30
  delay: 10
  until: coredns_cm.rc == 0
  changed_when: false
  run_once: true

- name: Patch CoreDNS to force TCP and external DNS
  ansible.builtin.shell: |
    set -o pipefail
    /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get configmap rke2-coredns-rke2-coredns -n kube-system -o yaml | \
    sed 's|forward . /etc/resolv.conf|forward . 8.8.8.8 1.1.1.1 {\n           force_tcp\n        }|g' | \
    /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml apply -f -
  args:
    executable: /bin/bash
  register: patch_coredns
  changed_when: "'configured' in patch_coredns.stdout"
  run_once: true

- name: Restart CoreDNS deployment to apply new DNS settings
  ansible.builtin.command:
    cmd: /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml rollout restart deployment rke2-coredns-rke2-coredns -n kube-system
  when: patch_coredns.changed
  run_once: true