apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: jenkins-agent
spec:
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  containers:
    - name: jnlp
      image: <YOUR_JENKINS_AGENT_IMAGE>
      tty: true
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
    - name: kaniko
      image: <YOUR_KANIKO_IMAGE>
      command: ["/busybox/cat"]
      tty: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      volumeMounts:
        - name: build-cache
          mountPath: /cache
    - name: trivy
      image: <YOUR_TRIVY_IMAGE>
      command: ["/bin/sh"]
      tty: true
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
    - name: helm
      image: <YOUR_HELM_IMAGE>
      command: ["/bin/sh"]
      tty: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
  volumes:
    - name: build-cache
      persistentVolumeClaim:
        claimName: <YOUR_JENKINS_AGENT_CACHE_PVC>