---
- name: Restart RKE2 agent
  ansible.builtin.systemd:
    name: rke2-agent.service
    state: restarted

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted